# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4458dbc89aa935f010193a1b6e7761d6ad2a54ee08509d757ddf07b6b9bc511e0d743aad36b81cd1863dc706afc4177976c506370afcfc138d3758f5600b492e

test:
  secret_key_base: b26e11c905c10fe07dfdb7c1608a1f38bf47952e2216027dc620b25af3fbdd1d677b0c1893cec7edcf364e74604445722e94267dc713f6a2ef147aa0b06d2f68

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
